# Admin data

```{r}
library(httr)
library(jsonlite)
library(dplyr)
library(stringr)

# API endpoint
api_url <- "https://www.cbn.gov.ng/api/GetConsExpSurvReports?format=json"

ddir <- file.path(getwd(), 'data')

ces_dir <- file.path(ddir, "consumer_exp_surv")
if (!dir.exists(ces_dir)){
  
  dir.create(ces_dir)
    
  # Fetch JSON
  res <- httr::GET(api_url)
  Sys.sleep(1)
  data <- jsonlite::fromJSON(content(res, "text"))

  # Base domain
  base <- "https://www.cbn.gov.ng"

  # Build full dataset
  df <- data %>%
    mutate(
      full_url = paste0(base, link),   # convert relative → absolute
      full_url = str_replace_all(full_url, " ", "%20")  # encode spaces
    ) %>%
    select(
      id,
      refNo,
      title,
      date = documentDate,
      filesize,
      full_url
    )

  write.csv(df, file.path(ces_dir,'consumer_expectation_survey.csv'))

}
```
```{r}

bes_dir <- file.path(ddir, "business_exp_surv")

if (!dir.exists(bes_dir)){
  dir.create(bes_dir)

  # API endpoint
  api_url <- "https://www.cbn.gov.ng/api/GetBusExpSurvReportS?format=json"

  # Fetch JSON
  res <- httr::GET(api_url)
  Sys.sleep(1)
  data <- jsonlite::fromJSON(content(res, "text"))

  # Base domain
  base <- "https://www.cbn.gov.ng"

  # Build full dataset
  df <- data %>%
    mutate(
      full_url = paste0(base, link),   # convert relative → absolute
      full_url = str_replace_all(full_url, " ", "%20")  # encode spaces
    ) %>%
    select(
      id,
      refNo,
      title,
      date = documentDate,
      filesize,
      full_url
    )

  write.csv(df, file.path(bes_dir, 'business_expectation_survey.csv'))

}
```
